import { d as defineEventHandler, c as getRequestLocale, aN as getUserSession, bD as endWebSession, X as clearUserSession } from '../../../nitro/nitro.mjs';
import '@adonisjs/hash';
import '@adonisjs/hash/drivers/scrypt';
import 'node:crypto';
import 'drizzle-orm';
import 'crypto';
import 'fs';
import 'path';
import 'node:http';
import 'node:https';
import 'node:events';
import 'node:buffer';
import 'node:fs';
import 'node:path';
import 'node:async_hooks';
import 'postgres';
import 'drizzle-orm/postgres-js';
import 'drizzle-orm/d1';
import '@libsql/client';
import 'drizzle-orm/libsql';
import 'mysql2/promise';
import 'drizzle-orm/mysql2';
import 'drizzle-orm/pg-core';
import 'drizzle-orm/sqlite-core';
import 'drizzle-orm/mysql-core';
import 'maxmind';
import 'node:url';
import '@iconify/utils';
import 'consola';
import 'zod';

const logout_post = defineEventHandler(async (event) => {
  var _a;
  const locale = getRequestLocale(event);
  const session = await getUserSession(event).catch(() => null);
  if (session == null ? void 0 : session.sessionId) await endWebSession(session.sessionId, Number((_a = session.user) == null ? void 0 : _a.id) || void 0);
  await clearUserSession(event);
  return { message: locale === "zh" ? "\u5DF2\u6210\u529F\u9000\u51FA\u767B\u5F55" : "Logged out successfully" };
});

export { logout_post as default };
